apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/auth-mongo-depl.yaml
      - ./infra/k8s/auth-depl.yaml
      - ./infra/k8s/gig-mongo-depl.yaml
      - ./infra/k8s/gig-depl.yaml
      - ./infra/k8s/admin-mongo-depl.yaml
      - ./infra/k8s/admin-depl.yaml
      - ./infra/k8s/profile-mongo-depl.yaml
      - ./infra/k8s/profile-depl.yaml
      # - ./infra/k8s/review-mongo-depl.yaml
      # - ./infra/k8s/review-depl.yaml
      - ./infra/k8s/nats-depl.yaml
build:
  local:
    push: false
  artifacts:
    - image: malakboudaa/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: malakboudaa/profile
      context: profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: malakboudaa/gig
      context: gig
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: malakboudaa/admin
      context: admin
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: malakboudaa/review
      context: review
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
